PR - Registration/api
Full-Stack-Projects/taskagile-backend pull request #1
Opened 2021-03-02 22:32 UTC by GersonVallejos

2021-03-03 03:07 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/controller/UserController.java
> +@RequestMapping("/v1")
Add users on the API path

2021-03-03 03:23 UTC, cvallejosh1 requested changes
Fix the comments

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/model/User.java
> +import javax.persistence.*;
Avoid using wildcards on imports

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/service/UserService.java
> +        if(userFound.isPresent()){
Use blank spaces after the if. Use google's style guide and reformat the code.

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/service/UserService.java
> +            throw new FieldAvailableException("Username not available");
When the user already exists use a better custom exception like UserAlreadyExistsException. Or a Generic one where you can have a type where you can indicate what kind of exception it is under your domain.

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/service/UserService.java
> +            throw new FieldAvailableException("Email not available");
Same as the previous comment. Use a better name for custom exceptions.

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/repository/UserRepository.java
> +    public Optional<User> findByUsername(String username);
Interface methods are implicitly public. It's redundant to add a public modifier

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/exception/CustomDetailException.java
> +
Use an appropriate name. It's not actually an exception is more like an error response.

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/exception/CustomExceptionHandler.java
> +public class CustomExceptionHandler{
Use a better name like ApiExceptionHandler, RestApiExceptionHandler, RestExceptionHandler

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/controller/UserController.java
> +import com.backend.taskagile.model.User;
Remove unused imports

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/exception/FieldValidationException.java
> +package com.backend.taskagile.exception;
From where this exception is being used or thrown? I think it's never used.

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/controller/UserController.java
> +    public ResponseEntity<User> registerUser(@Valid @RequestBody User user) throws Exception {
Repository entity objects should not be used on the controller layer. Create a new one considered as domain or DTO class.

2021-03-03 03:23 UTC, cvallejosh1 commented on src/main/java/com/backend/taskagile/controller/UserController.java
> +    public ResponseEntity<User> registerUser(@Valid @RequestBody User user) throws Exception {
If you add @Valid annotation. Take into consideration what kind of exception will be thrown when something breaks the rules that make it an invalid value. So that exception should be mapped on the exception handler.

2021-03-03 11:15 UTC, GersonVallejos commented on src/main/java/com/backend/taskagile/controller/UserController.java
> +@RequestMapping("/v1")
"_users_" Added on path

2021-03-03 11:16 UTC, GersonVallejos commented on src/main/java/com/backend/taskagile/repository/UserRepository.java
> +    public Optional<User> findByUsername(String username);
"public" implementations removed

2021-03-03 11:18 UTC, GersonVallejos commented on src/main/java/com/backend/taskagile/exception/CustomDetailException.java
> +
Name class changed to "ErrorResponseDetail"

2021-03-03 11:20 UTC, GersonVallejos commented on src/main/java/com/backend/taskagile/exception/CustomExceptionHandler.java
> +public class CustomExceptionHandler{
Modified to "ApiExceptionHandler"

2021-03-03 11:23 UTC, GersonVallejos commented on src/main/java/com/backend/taskagile/controller/UserController.java
> +import com.backend.taskagile.model.User;
Unused imports removed

2021-03-03 14:33 UTC, GersonVallejos commented on src/main/java/com/backend/taskagile/service/UserService.java
> +            throw new FieldAvailableException("Username not available");
Class name exception modified to "UserAlreadyExistsException"

2021-03-03 14:33 UTC, GersonVallejos commented on src/main/java/com/backend/taskagile/service/UserService.java
> +            throw new FieldAvailableException("Email not available");
Class name exception modified to "UserAlreadyExistsException"

2021-03-03 14:34 UTC, GersonVallejos commented on src/main/java/com/backend/taskagile/exception/FieldValidationException.java
> +package com.backend.taskagile.exception;
Class removed

2021-03-03 15:38 UTC, GersonVallejos commented on src/main/java/com/backend/taskagile/service/UserService.java
> +        if(userFound.isPresent()){
Google's style applied as a new scheme

2021-03-03 15:39 UTC, GersonVallejos commented on src/main/java/com/backend/taskagile/model/User.java
> +import javax.persistence.*;
Applied

2021-03-08 00:31 UTC, cvallejosh1 approved these changes

2021-03-08 17:37 UTC, merged